### ISSUE TITLE
Adding the plugin to the asdf plugin repo

### ISSUE THREAD

**Issue by rolandtritsch** [benthosdev/benthos-asdf#3]
@mihaitodor Just tracking this here this way: I am also working to add the plugin to the asdf-plugin repo. - https://github.com/asdf-vm/asdf-plugins/pull/736

I will close the issue when the PR above is merged.

**Comment by rolandtritsch** [comment]
@mihaitodor Works now ...
```
asdf plugin add benthos
asdf install benthos latest
asdf global benthos latest
```
Closing the issue.

**Comment by mihaitodor** [comment]
Awesome, thank you so much for all the work you put in to make this work @rolandtritsch! ❤️
